### ISSUE TITLE
Converting sparse IndexedSlices to a dense Tensor of unknown shape. 

### ISSUE THREAD

**Issue by Anymake** [matterport/Mask_RCNN#116]
Thanks for your great work. I train maskrcnn on my own dataset, and it worked. but in the half of the training, it throws the warning as below:

/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:95: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
/home/renren/anaconda3/lib/python3.6/site-packages/keras/engine/training.py:2057: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the`keras.utils.Sequence class.
  UserWarning('Using a generator with `use_multiprocessing=True`'
/home/anaconda3/lib/python3.6/site-packages/scipy/ndimage/interpolation.py:600: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
/home/anaconda3/lib/python3.6/site-packages/scipy/ndimage/interpolation.py:600: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)

**Comment by waleedka** [comment]
I get these warnings as well. They don't cause any issues:

1. The first is a TF warning about an operation that *might* consume a lot of memory, but it doesn't seem to be a problem. 
2. The Keras warning about possible duplication of data is not critical. Having a few images duplicated is not a problem. It would be better, though, to switch to Keras's new dataset functions since they seem to be the new recommended approach and they work better on Windows. I'll try to do that if I get some free time, but if someone else wants to take a stab at it that would be great.
3. The Scipy warning is pretty annoying. It's basically an announcement about a breaking change they implemented recently. I think it shouldn't be logged as a warning, or at least they should provide a way to turn it off.
