### ISSUE TITLE
size of mask and image

### ISSUE THREAD

**Issue by kimchicanh** [matterport/Mask_RCNN#129]
Hi,

Thanks for your project, I am training on my dataset and have some issues:
image of dataset is not fix size so mask is not fix size too. when I put it to form of you at line 
            self.add_image("shapes", image_id=id, path=imgs[id],
                           width=width, height=height)
Do I need change to real size of image

Thanks

**Comment by waleedka** [comment]
No you don't need to. `add_image()` only adds the image details, not the image itself. The `load_image()` and `load_mask()` functions load the image and mask resize them to the right size. 

Note that `add_image()` doesn't need the `height` and `width` params in most cases. The COCO dataset is an exception, and that's why you see them passed in `coco.py` because in COCO the masks are created dynamically and require knowing the original image size. For most datasets you don't need to pass width and height.

**Comment by hdjsjyl** [comment]
@waleedka , I am very fused that which parts load image data, because, I want to resize my own dataset to speed training. I do not find this part. thanks
