### ISSUE TITLE
pycocotools setup errors

### ISSUE THREAD

**Issue by Yiman-GO** [matterport/Mask_RCNN#133]
I download file from https://github.com/waleedka/coco. Then I placed the file in Mask_RCNN-master, went to the coco-master/PythonAPI and run make. 

BUT, when i run the demo.ipynb, there is an error said that " ModuleNotFoundError: No module named 'pycocotools'.". is there anyone know why it is happened? 

I also tried the replace python with python3 in Makefile.

**Comment by Yiman-GO** [comment]
I have solved this problem by copying the pycooctools to the file Mask_RCNN-master.

**Comment by ps48** [comment]
Only using the **make** file will actually use Makefile to build the program whereas **make install** uses Makefile to install the program. Hence try make install so that the path is added to python paths and you may use the pycocotools module from anywhere in the system.  
Just in case you are not willing it to install just make & add the sys.path.append('/path/to/the/coco/repo') in coco.py

**Comment by jmtatsch** [comment]
@Yiman-GO  why don't you just `python3 setup.py install` it?

**Comment by Dive-frank** [comment]
i have meet this problem,you need to ensure you pyccotools make bypython3,

    # install pycocotools locally
    python3 setup.py build_ext --inplace
    # install pycocotools to the Python site-packages
    python3 setup.py build_ext install

**Comment by Yiman-GO** [comment]
@jmtatsch @Dive-frank  thanks for your answers. I did change python to python3, but it's doesn't work until I extract the file pycocotools to the  Mask_RCNN-master. and now, it works well.
