### ISSUE TITLE
Get feature vector of masked region

### ISSUE THREAD

**Issue by VellalaVineethKumar** [matterport/Mask_RCNN#1456]
can anyone please help me get a feature vector of the masked region? I'm really struggling to get it
I first referred to this Issue: #1249 and then #1190 i did all the changes mentioned there but i get errors like "positional argument required "roi_pooled_features". I'm still stuck here for a month and any help would be really appreciated.

**Comment by kielnino** [comment]
Here you go [model.py](https://gist.github.com/kielnino/3965d905a921abbe29a7c89af5ba1114)
The feature vectors are stored as `features` in the results dict (see Line 2540)

**Comment by VellalaVineethKumar** [comment]
@kielnino Thank you very much for your quick response. i replaced the model.py file with your model.py file 
1) Are you using **demo.py** to get the **results** dictionary including features?
2) Are you using **inspect_model.py** to get the **results** dictionary including features?
i tried using both but when i try to print **results[0].keys()** i get only **dict_keys(['rois', 'class_ids', 'scores', 'masks'])** as output. 
where am i going wrong any suggesstions?

**Comment by kielnino** [comment]
I'm using neither of them, but as `model.detect` returns the result (of course only in inference mode), it should work in the demo applications too.

**Comment by VellalaVineethKumar** [comment]
@kielnino Do you mean just use **print(model.detect())** in the jupyter notebook?

**Comment by VellalaVineethKumar** [comment]
Heres what im getting after running the **inspect_model.py** demo file.
i cannot see the features in the **results** returned by **model.detect([image], verbose=1)**
![snap](https://user-images.githubusercontent.com/31627944/56526164-98245480-6569-11e9-8db6-90292b1d8643.png)

**Comment by VellalaVineethKumar** [comment]
This output is from the demo.ipynb after replacing the model file
![newsnap](https://user-images.githubusercontent.com/31627944/56527694-ab382400-656b-11e9-8721-b410ceccf0ee.png)

**Comment by raynejan** [comment]
@kielnino Thanks for posting your model.py. 

Originally, I was getting an empty array as an output when I tried to print r['features'], but that was because I manually made additions to the original model.py. But when I compared your model.py to that of the original,  I found 20 differences, most of which include the  addition of feature_maps at various points (e.g., original model.py has _def refine_detections_graph(rois, probs, deltas, window, config):_ and your model.py has _def refine_detections_graph(rois, probs, deltas, window, feature_maps, config):_). 

When I replaced the original file with your model.py entirely in the mrcnn folder and re-ran my code, I kept getting the following message:
"'_CocoSynthConfig' object has no attribute 'PRE_NMS_LIMIT'_"

This error is coming up exclusively when I use your model.py file. When I've reverted back to the old model.py file, the error no longer exists. I've tried to look up a potential solution online but haven't found one yet. I was wondering if you could possibly shed some light to what may be happening?

Thanks in advance.

**Comment by raynejan** [comment]
@kielnino It turned out to be a simple fix. I simply added an arbitrary "PRE_NMS_LIMIT" value into my "CoCoSynthConfig". I've re-run everything and can see the features (in an array form) are appearing in my output. 

Just to quench my inquisitive mind, would you be able to provide an insight into why I had to specify a PRE_NMS_LIMIT when using your model.py? That chunk of the code doesn't change between the original and modified model.py.

Thanks again for posting your model.py. It really is greatly appreciated and has been of immense help.

**Comment by VellalaVineethKumar** [comment]
@kielnino Thanks for sharing it really helped me!

**Comment by ghost** [comment]
So could you plz send the model.py to me? I'm suffering the same problem, and I can't download the file.
email: LZ_Jaja@126.com
Thanks in advance!
