### ISSUE TITLE
Issue in utils.compute_ap()

### ISSUE THREAD

**Issue by akrsrivastava** [matterport/Mask_RCNN#1630]
I am getting an issue with line no 734
 `recalls = np.cumsum(pred_match > -1).astype(np.float32) / len(gt_match)`

What happens if there is actually no object instance on an image, but my model is predicting an object? gt_bbox will be empty , hence len(gt_match) would be zero. This division by zero will fail. I am actually facing this problem, where I get the error message. I have an image in the test folder, but it has no object instance for the class which I am training for.

> \mrcnn\utils.py:734: RuntimeWarning: invalid value encountered in true_divide

Thanks!
Amit

**Comment by mangalbhaskar** [comment]
@akrsrivastava 

If no object instance present in an image, hence no (zero) annotation for that image; that means there would be no prediction that can match to the ground truth hence numerator of precision and recalls (i.e. True positives) would be 0 i.e. precisions would be zero array. Thus, you can try to fix it like below:
```python
recalls = np.zeros(len(pred_match), dtype='float32') if np.sum(precisions, dtype=int) == 0 else np.cumsum(pred_match > -1).astype(np.float32) / len(gt_match)
```
I am curious to know your reasons why would you have such a image in the dataset split at first place and why would you train/evaluate on an image?

Additionally, these are the situations where you would like to calculate the confusion matrix because now both precisions and recalls would be zero.

**Comment by akrsrivastava** [comment]
Wow, I had forgotten about this ticket. Closing this off as dont exactly remember the context of this issue now. Thanks for your response though !

**Comment by kecyarchana** [comment]
Hello, have you figured out the issue of RuntimeWarning: invalid value encountered in true_divide

I am trying to calculate mean average precision as a callback for my validation dataset during training in every 5 epochs but I am getting nan values and a runtime warning as below.

![mAP_nan](https://user-images.githubusercontent.com/22496671/148531727-488942a3-9239-4b7c-a998-c23b713e4eb1.PNG)

I cannot figure out what might be the cause as my training and validation dataset has only the images with the objects in it and their respective annotations as shapefiles. Any help would be greatly appreciated.

Thanks

**Comment by SalmaZakaria** [comment]
@kecyarchana 
Have you solved it? I have the same issue
