### ISSUE TITLE
GPU usage during training - Shapes sample

### ISSUE THREAD

**Issue by noamnav** [matterport/Mask_RCNN#1783]
Trying to follow the Shapes sample,  I cannot get past Epoch 1/1 - the script seems to be running, however no sign of processing and task is never completed. 

When examining the task manager, I have noticed GPU is at ~0% (see below). However all signs are the GPU is tuned and should be utilized by tensorflow. The following is received in the terminal:

_`_2019-10-07 21:24:16.026724: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Quadro K1100M, pci bus id: 0000:02:00.0, compute capability: 3.0)`_

Spec as follows:
Win 10
Python 36
keras 2.08
Tensorflow 1.5
GPU Quadro K1100M

Any ideas please?
Should the GPU appear very active whilst training?
If you have followed this sample, can you please post your terminal script for the training part?

![image](https://user-images.githubusercontent.com/6349581/66346321-d5c73f00-e949-11e9-87cc-d4bea9e87c71.png)

![image](https://user-images.githubusercontent.com/6349581/66346748-bc72c280-e94a-11e9-88bd-25d94cfe4200.png)

thanks

**Comment by noamnav** [comment]
Have also noticed several difference in the configuration file between the sample and its reproduction on my machine that I cannot explain:
- backbone shapes
- GRADIENT_CLIP_NORM             
- RPN_ANCHOR_STRIDE
- TRAIN_ROIS_PER_IMAGE           
- ...and a few others.

@waleedka can you please post the environment configuration used originally for this sample?

Thanks

Sample:
```
BACKBONE_SHAPES                [[32 32]
 [16 16]
 [ 8  8]
 [ 4  4]
 [ 2  2]]
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     8
BBOX_STD_DEV                   [ 0.1  0.1  0.2  0.2]
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0.5
DETECTION_NMS_THRESHOLD        0.3
GPU_COUNT                      1
IMAGES_PER_GPU                 8
IMAGE_MAX_DIM                  128
IMAGE_MIN_DIM                  128
IMAGE_PADDING                  True
IMAGE_SHAPE                    [128 128   3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.002
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MAX_GT_INSTANCES               100
MEAN_PIXEL                     [ 123.7  116.8  103.9]
MINI_MASK_SHAPE                (56, 56)
NAME                           SHAPES
NUM_CLASSES                    4
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        1000
POST_NMS_ROIS_TRAINING         2000
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (8, 16, 32, 64, 128)
RPN_ANCHOR_STRIDE              2
RPN_BBOX_STD_DEV               [ 0.1  0.1  0.2  0.2]
RPN_TRAIN_ANCHORS_PER_IMAGE    256
STEPS_PER_EPOCH                100
TRAIN_ROIS_PER_IMAGE           32
USE_MINI_MASK                  True
USE_RPN_ROIS                   True
VALIDATION_STEPS               50
WEIGHT_DECAY                   0.0001
```

When reproduced locally:
```
ACKBONE                       resnet101
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     8
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
COMPUTE_BACKBONE_SHAPE         None
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0.5
DETECTION_NMS_THRESHOLD        0.3
FPN_CLASSIF_FC_LAYERS_SIZE     1024
GPU_COUNT                      1
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_GPU                 8
IMAGE_CHANNEL_COUNT            3
IMAGE_MAX_DIM                  128
IMAGE_META_SIZE                16
IMAGE_MIN_DIM                  128
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              square
IMAGE_SHAPE                    [128 128   3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
LOSS_WEIGHTS                   {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_mask_loss': 1.0}
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MAX_GT_INSTANCES               100
MEAN_PIXEL                     [123.7 116.8 103.9]
MINI_MASK_SHAPE                (56, 56)
NAME                           shapes
NUM_CLASSES                    4
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        1000
POST_NMS_ROIS_TRAINING         2000
PRE_NMS_LIMIT                  6000
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (8, 16, 32, 64, 128)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
RPN_NMS_THRESHOLD              0.7
RPN_TRAIN_ANCHORS_PER_IMAGE    256
STEPS_PER_EPOCH                100
TOP_DOWN_PYRAMID_SIZE          256
TRAIN_BN                       False
TRAIN_ROIS_PER_IMAGE           32
USE_MINI_MASK                  True
USE_RPN_ROIS                   True
VALIDATION_STEPS               5
WEIGHT_DECAY                   0.0001
```

**Comment by bichson2002** [comment]
Trying to set use_multiprocessing=False in model.py.

**Comment by noamnav** [comment]
@bichson2002 thanks, a simple question though:
when modifying the model.py file within the mrcnn file it seems no changes come into effect.
checking the source of model.py after loading brings:

![image](https://user-images.githubusercontent.com/6349581/66478053-6b211b00-ea91-11e9-96fb-be6b18d5de7d.png)


which to my understanding means files are loaded from the egg file which I do not have direct access to. Is one expected to upzip the egg file, edit it and re-egg it? seems unlikely so I am probably missing something.

Thanks

**Comment by WLChopSticks** [comment]
> Trying to set use_multiprocessing=False in model.py.

Here I meet similar issue and I will raise error when start to train the network.
Whatever I set use_multiprocessing is True or False, the error is the same.

Following is my errors:

Starting at epoch 0. LR=0.001

Checkpoint Path: C:\Users\wang\Documents\Obj_Dection_Segmentation\code\mask_RCNN\logs\shapes20191011T2143\mask_rcnn_shapes_{epoch:04d}.h5
Selecting layers to train
fpn_c5p5               (Conv2D)
fpn_c4p4               (Conv2D)
fpn_c3p3               (Conv2D)
fpn_c2p2               (Conv2D)
fpn_p5                 (Conv2D)
fpn_p2                 (Conv2D)
fpn_p3                 (Conv2D)
fpn_p4                 (Conv2D)
In model:  rpn_model
    rpn_conv_shared        (Conv2D)
    rpn_class_raw          (Conv2D)
    rpn_bbox_pred          (Conv2D)
mrcnn_mask_conv1       (TimeDistributed)
mrcnn_mask_bn1         (TimeDistributed)
mrcnn_mask_conv2       (TimeDistributed)
mrcnn_mask_bn2         (TimeDistributed)
mrcnn_class_conv1      (TimeDistributed)
mrcnn_class_bn1        (TimeDistributed)
mrcnn_mask_conv3       (TimeDistributed)
mrcnn_mask_bn3         (TimeDistributed)
mrcnn_class_conv2      (TimeDistributed)
mrcnn_class_bn2        (TimeDistributed)
mrcnn_mask_conv4       (TimeDistributed)
mrcnn_mask_bn4         (TimeDistributed)
mrcnn_bbox_fc          (TimeDistributed)
mrcnn_mask_deconv      (TimeDistributed)
mrcnn_class_logits     (TimeDistributed)
mrcnn_mask             (TimeDistributed)
WARNING:tensorflow:From C:\Users\wang\anaconda3\lib\site-packages\keras\optimizers.py:711: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

C:\Users\wang\anaconda3\lib\site-packages\tensorflow\python\ops\gradients_util.py:93: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
C:\Users\wang\anaconda3\lib\site-packages\tensorflow\python\ops\gradients_util.py:93: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
C:\Users\wang\anaconda3\lib\site-packages\tensorflow\python\ops\gradients_util.py:93: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
WARNING:tensorflow:From C:\Users\wang\anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:675: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From C:\Users\wang\anaconda3\lib\site-packages\keras\callbacks.py:705: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

WARNING:tensorflow:From C:\Users\wang\anaconda3\lib\site-packages\keras\callbacks.py:708: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

Traceback (most recent call last):
  File "C:\Users\wang\anaconda3\lib\site-packages\keras\utils\data_utils.py", line 710, in get
    raise StopIteration()
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/wang/Documents/Obj_Dection_Segmentation/code/mask_RCNN/samples/shapes/shape_demo.py", line 254, in <module>
    layers='heads')
  File "C:\Users\wang\Documents\Obj_Dection_Segmentation\code\mask_RCNN\mrcnn\model.py", line 2375, in train
    use_multiprocessing=False,
  File "C:\Users\wang\anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\wang\anaconda3\lib\site-packages\keras\engine\training.py", line 2065, in fit_generator
    generator_output = next(output_generator)
RuntimeError: generator raised StopIteration
Epoch 1/1

Process finished with exit code 1

**Comment by noamnav** [comment]
Initial issue solved: simply a case of too weak GPU. do not try and run with GTX 1050ti.

**Comment by Dayan-Zhanchi** [comment]
@noamnav 
Even if your GPU was too weak, isn't it still weird that you got 0% on the GPU usage, indicating that it's not used at all? I mean even if it's weak, it just means that it should take a long time for it to train, but that your GPU usage should still be > 0%?

**Comment by noamnav** [comment]
Not quite sure but potentially the answer is no as there's a memory
threshold that you won't be able to pass.

Try using Google colab instead

**Comment by Dayan-Zhanchi** [comment]
@noamnav 
Okay thanks for replying! I got a nvidia rtx 2060 (6GB memory), and have the same problem, that it gets stuck on epoch 1/1 and that the GPU usage is 0%. I guess that memory threshold you mentioned might be the reason for my problem, I thought that reducing the IMAGE_PER_GPU to 1 (it was initially set to 2 for 12GB memory) in the config file sufficed, but I guess not.

**Comment by suchiz** [comment]
@Dayan-Zhanchi I also encoutered this: Here is my thread https://github.com/matterport/Mask_RCNN/issues/1823

Working fine on GTX 1080 8Go IMAGE_PER_GPU = 1

**Comment by Dayan-Zhanchi** [comment]
Since you seem to not be answering in our own thread I'll repost it here:

@suchiz Did you have to change anything more in the mask rcnn code apart from adjusting the IMAGE_PER_COUNT = 1 instead of 2? I believe my teammate has the exactly the same graphic card with the same memory as yours, but he still gets the same problem as initially presented in this issue, meaning that the training gets stuck on the very first epoch and doesn't finish at all (the GPU usage stays pretty much at 0-2%, which may indicate that it's not being used). We've checked that tensorflow-gpu is installed + that tensorflow is able to use the GPU. We changed the IMAGE_PER_COUNT variable to 1, so that less memory is used, but ye, we still encounter the same problem.

Thanks in advance!

**Comment by suchiz** [comment]
@Dayan-Zhanchi I'm really sorry, I saw your post and totally forgot to reply. Sorry to ask those basics, but when you said tensorflow-gpu is working, does it shows that it is using Cuda and Cudnn in the beginning of the training ? Like the initialisation of tensorflow-gpu. If yes, maybe check the mini mask parameter in Config, it can save a lot of memory aswell ... because my GPU is 7.x/8Go during the training ... Not much memory left with only 1 image... and maybe try to force resizing to the minimum size required IMAGE_MIN_DIM = 800 (which I did). The CNN is still pretty efficient on 800*800... Keep me in touch and good luck !

**Comment by Dayan-Zhanchi** [comment]
@suchiz 
Thanks for the reply and it's np. Yes the tensorflow-gpu seems to work, but still it doesn't seem to be used during training. What exactly do you mean by 7.x/8Go? And what did you set the mini-mask parameter in the config file, if you did?

**Comment by suchiz** [comment]
@Dayan-Zhanchi I meant that during the training, with only 1 image (800x800) and mini mask (56x56), my GPU memory is almost full (7.x/8Go). So, just a bigger image, or a bigger mask would exceed ... I think. Not sure about what I'm saying, I'm just proposing solutions.

Just set the use_mini-mask to true, and the default minishape is already set to 56x56

**Comment by Dayan-Zhanchi** [comment]
@suchiz 
So we solved it now. We just had to do the following changes to the train function on the arguments of the keras_model.fit_generator in the model.py:

- Change the use_multiprocessing to False instead of True
- Change the workers to 1 instead of 0

It seems that on Windows the workers are set to 0 and we somehow had the use_multiprocessing set to True. I think this made it so that no GPU were used when training.

Anyways, thanks for the help!

**Comment by NickosKal** [comment]
Hey @Dayan-Zhanchi I try to run Mask-RCNN on my own dataset 
- multiprocessing is False 
- workers are to 1
- verbose is set to 1
Still when I run the code it stops at epoch 1 without showing any error. I don't run the programm on a GPU for the reason that I don't have an Nvidia graphics card any suggestion?

I am using tensorflow 1.15.3 
and keras 2.1.6

**Comment by suchiz** [comment]
@NickosKal Mask RCNN is too big to be run on a CPU. It takes forever that's why you haven't any errors. Also if you use a GPU. You will need an 8Go for an image of 1024*1024. It takes 7.1Go memory on my RTX 2060.

**Comment by NickosKal** [comment]
@suchiz I see so that is the problem because when I also trace the code it freezes at epoch 1 
So I guess I will use a diffrent model.
Thanks!
