### ISSUE TITLE
Single mask per RoI

### ISSUE THREAD

**Issue by AlexTS1980** [matterport/Mask_RCNN#180]
This one thing keeps baffling me: if you use FCN for each RoI, it returns the binary mask by argmax'ing each pixel (like FCN in Long, Shelhamer (2015) for example). How does MaskRCNN learns to return exactly one mask in each bounding box? Are non-background pixles that don't belong to the largest mask suppressed in some way?

**Comment by jocicmarko** [comment]
Mask R-CNN extends Faster R-CNN. Faster R-CNN had a classifier for each bounding box, and Mask R-CNN predicts masks for each class within the bounding box, but returns only the mask for the class predicted by the classifier.

**Comment by AlexTS1980** [comment]
Yes I understand this: there's no competition between classes per pixel, as in FCN (Long, Shelhamer), therefore sigmoid is used rather than softmax. I meant something a bit different - and after some testing it turned out I was wrong - there may be more than 1 mask PER bounding box. If you look at this output , the bbox with score=1 actually produced two blue masks. So this is possible, just kinda unlikely due to the size of the bboxes
![two_masks](https://user-images.githubusercontent.com/8479872/34835437-b6f028b8-f6ec-11e7-9263-b1105f775ea8.png)

**Comment by jocicmarko** [comment]
Yes, that is possible, but you are actually talking about "blobs" and not masks. There are no constrains on the number of blobs per bounding box, which I think is actually a plus, since that way you can have masks for occluded and partially visible objects. 
You can easily post-process the mask and keep only one (say, the biggest) blob.
However, it would take more troubles if you would like to incorporate this behavior in the model itself :)

**Comment by AlexTS1980** [comment]
If I understand MRCNN correctly, it outputs binary mask per RoI, which means you have only object/background pixels in the bounding  box, with 'blob' being the groups of pixels for the object. What I observed in my data (As you see in the picture) typically there is a single mask in the bbox, but there are exceptions.  

'You can easily post-process the mask and keep only one (say, the biggest) blob' - wouldn't that be cheating? Of course if you remove small blobs, overall precision will grow.

**Comment by John1231983** [comment]
Hi @AlexTS1980: I want to obtain a probability map for each class, instead of binary map. Hence, I will use softmax loss. Do you think it is possible? Which function should I change?

**Comment by FruVirus** [comment]
@John1231983 

The masks generated by build_fpn_mask_graph() for the targets are probability maps, not binary maps. The ground-truth masks have to be binary maps by their nature since it doesn't make sense for them to be probabilities. mrcnn_mask_loss_graph() is calculating the softmax loss already.

**Comment by John1231983** [comment]
Thanks. For my task, I would like to obtain the softmax output of prediction. Which function should I use? The softmax output similar the output of UNet and FCN paper

**Comment by FruVirus** [comment]
The probability maps are given as the output corresponding to the last TimeDistributed layer in build_fpn_mask_graph().
