### ISSUE TITLE
Configuration for my own dataset (RFI detection)

### ISSUE THREAD

**Issue by lean2206** [matterport/Mask_RCNN#1916]
Hi!
I have images of size 533x50 that contain radio frecuency interference. They are labeled as Narrow Band (NB) Intermediate Band (IB) and Wide Band (WB). 

![example2](https://user-images.githubusercontent.com/50563528/70852721-96562b00-1e83-11ea-8e31-6abc7e1a3230.PNG)

![example](https://user-images.githubusercontent.com/50563528/70851992-eaa8dd00-1e7a-11ea-8638-b42e92d6c586.PNG)

All of the objects (RFI) heights are always 50px, so the classification is based on the widths.
The minimum width in the dataset is 5px (NB) and the maximum is 232px (WB)
My question is, what parameters should i have to modify to adapt the model to my images?

My actual configuration setting is this:
NUM_CLASSES = 1 + 3
GPU_COUNT = 1
IMAGES_PER_GPU = 1
IMAGE_CHANNEL_COUNT = 1
MEAN_PIXEL = np.array([128])             <-----------( I use grey scale images)
BACKBONE = "resnet50"
IMAGE_RESIZE_MODE = "none"             <-----------(!!!)
IMAGE_MIN_DIM = 50             <-----------(!!!)
IMAGE_MAX_DIM = 553             <-----------(!!!)
DETECTION_MAX_INSTANCES = 50
DETECTION_MIN_CONFIDENCE = 0.7
RPN_ANCHOR_SCALES = (5, 7, 9, 50, 32, 64, 128, 256, 512)             <-----------(!!!)
RPN_ANCHOR_RATIOS = [0.5, 1, 2]             <-----------(!!!)

I don't know how to configure exactly the parameters marked with an arrow

Thank you

**Comment by nyinyinyanlin** [comment]
@lean2206 Did you have any positive results from your project? I am trying to figure out the same thing on my own dataset. As far as I understand, RPN_ANCHOR_RATIOS are simple, in your case NBs could be a lot less than w/h ratio of 0.5. You should lower it to as low as 0.2 or something. Same goes with WB, you should increase the ratio to more than 2. But regarding RPN_ANCHOR_SCALES and MEAN_PIXELS, I am trying to figure out how to make sense out of it. In my case, I am detecting buildings, with ground sample distance 0.5m per pixel and one building could be as small as 5 meters width or height, I suppose it could be 10 for the lowest RPN_ANCHOR_SCALE. But I honestly do not have any idea how MEAN_PIXELS are calculated and the pixel depth of the image data will have an impact on it I think. Any pointers would be appreciated.

**Comment by lean2206** [comment]
@nyinyinyanlin yes i did! you can see them in here https://github.com/lean2206/RFI-detection-and-classification-with-Mask-RCNN
Honestly this project was from 4 years ago and I dont remember the specific details of it (configs). I just did little to none modifications to the default configuration and worked just fine for me (better than I expected). Maybe you should give it a try and see what comes out of it

**Comment by nyinyinyanlin** [comment]
@lean2206 Thanks for your reply. And congratulations!! That's a neat project and interesting. Basically, my project is just for building footprint extraction from VHR satellite images with spatial resolutions around 0.5m per pixel. I have been getting okayish results from both training and inference, but bounding box losses from RPN and MaskRCNN are still high a bit, around 0.6 with a plateau around 0.5 best case scenario. This may be due to my object sizes not in align with default RPN ratios and scales.

Next thing is that I have been using satellite images with uint16 data types and there definitely will be a different mean values for pixels (and worst if my images include NODATA pixels with a very small/high values or 0.) This will have a big impact if MEAN_PIXEL values have a great contribution to model performance. I am investigating now on these matters.

I have noticed that your repository doesn't include your training configs but original MaskRCNN repo. Do you happen to have training configs available online for your model? Regardless, thank you very much for your help and if it is not convenient for you, please forget about the configs.
