### ISSUE TITLE
the relationship between STEPS_PER_EPOCH and value of IMAGES_PER_GPU * GPU_COUNT

### ISSUE THREAD

**Issue by yz-ju** [matterport/Mask_RCNN#2076]
I think STEPS_PER_EPOCH =traning_set / (IMAGES_PER_GPU * GPU_COUNT). But, there is a note about the STEPS_PER_EPOCH in the file of configure.py as follows:
Number of training steps per epoch
    # **This doesn't need to match the size of the training set**. 
How should I set the value of STEPS_PER_EPOCH？

**Comment by tomklaver1995** [comment]
You could choose this yourself but as you mention "STEPS_PER_EPOCH =traning_set / (IMAGES_PER_GPU * GPU_COUNT)" is a good starting point. This ensures that at every epoch your whole trainset is sent through the network, nothing more nothing less. 

This is commonly used because it makes it easy to track the performance of your model. So: if for example your training set is 500 images and you use a batch size of 1 and 1 gpu. After two epochs you passed your whole dataset two times through the network, but this would be exactly the same as setting step per epoch to a 1000 and let it run for one epoch.

Although it doesn't matter i would still recommend your approach to easier track the influence of different batch sizes and learning rates to the performance of your model.

**Comment by yz-ju** [comment]
Thanks for your reply.
