### ISSUE TITLE
Training on my own dataset

### ISSUE THREAD

**Issue by sirbastiano** [matterport/Mask_RCNN#2385]
Hi to everyone. I have jpg of my images and masks (I don't have annotations). How I can load this in datasets? What changes should I make in the Class Dataset?

Thank you for your time

**Comment by sainatarajan** [comment]
Instead of modifying the dataset class, you can convert the mask annotations into a JSON file whose format matches with the VIA Annotation tool.

I can give you a pseudo-code on how to do it:
For each image identify the contours (using OpenCV) and extract the contour points. Append this information into a dictionary and form a JSON structure that resembles the output format of the VIA Annotation tool.

**Comment by sirbastiano** [comment]
Yes thanks, all help appreciated

Il lun 12 ott 2020, 19:19 sainatarajan <notifications@github.com> ha
scritto:

**Comment by FabiolaL09** [comment]
@SirBastiano Hello! I have the same problem, do you know how to solve it?
I have the binary masks (I don't have annotations)) but I can't find the way to convert it to JSON format

**Comment by sirbastiano** [comment]
Fabiola sei italiana?

Il mer 11 nov 2020, 23:18 FabiolaL09 <notifications@github.com> ha scritto:

**Comment by jyothir07** [comment]
> @SirBastiano Hello! I have the same problem, do you know how to solve it?
> I have the binary masks (I don't have annotations)) but I can't find the way to convert it to JSON format

try this tutorial

https://patrickwasp.com/create-your-own-coco-style-dataset/

you may have to make few changes to make it work properly.
