### ISSUE TITLE
Shape mismatch error

### ISSUE THREAD

**Issue by Sharathnasa** [matterport/Mask_RCNN#24]
Hi @waleedka ,

Thanks a lot for an awesome repository. You've done good work. 
I'm trying to trying to trigger a training on own dataset which is of Coco dataset type, but less number of classes(only 5).

When I changed the the number classes to 5+1 in the coco.py and trigger a training using Coco pretrained model, I'm getting the shape mismatch error. 

Does this because the pretrained model is of 81 classes Or have I done any mistake? Please correct me if I'm wrong.

So does this mean, I need to start a new training from scratch for 5 classes?

Regards,
Sharath

**Comment by waleedka** [comment]
You guessed right, the mismatch is caused by the difference in the number of classes. You can either start training from scratch (not recommended), or start from ImageNet weights (better), or start from pre-trained COCO weights and skip loading the weights of the changed layers (best). 

Check the train_shapes notebook for an example of how to do the third option.

**Comment by Sharathnasa** [comment]
@waleedka

Thanks!!! I will go through it.

**Comment by Walid-Ahmed** [comment]
@Sharathnasa 
Can you please tell how you eventually made the training with your 5+1 classes?
Also please  advice how to put my dataset on Coco JSON format

Thanks,

Walid
