### ISSUE TITLE
Understanding MAX_GT_INSTANCES

### ISSUE THREAD

**Issue by YanWang2014** [matterport/Mask_RCNN#241]
Hi,

I am working on a task, where each image contains **120** objects at most. How should I set the following parameters? I believe their values are correlated

Thank you!

> RPN_TRAIN_ANCHORS_PER_IMAGE
> 
> TRAIN_ROIS_PER_IMAGE
> 
> MAX_GT_INSTANCES = 100
> 
> DETECTION_MAX_INSTANCES

**Comment by FruVirus** [comment]
As I understand it:

DETECTION_MAX_INSTANCES effectively takes the top DETECTION_MAX_INSTANCES scores proposals after NMS for object classification and BB regression in order to speed up inference time. Thus, it is only for inference, and not training.

MAX_GT_INSTANCES effectively puts an upper limit to the number of ground-truth object instances per image. Thus, you want to change this to 120.

TRAIN_ROIS_PER_IMAGE governs how many (good) positive + negative ROIs from the RPN to use for training the ODN network

RPN_TRAIN_ANCHORS_PER_IMAGE ....not sure yet since I haven't gotten to this part of the code yet

**Comment by YanWang2014** [comment]
Thank you
