### ISSUE TITLE
 ValueError: Tried to convert 'shape' to a tensor and failed. Error: None values not supported.

### ISSUE THREAD

**Issue by mlsy123** [matterport/Mask_RCNN#2737]
I have ran into an error while running this code below from . Any help would be appreciated

# Code
%Create model object in inference mode.
model = modellib.MaskRCNN(mode="inference", model_dir=MODEL_DIR, config=config)
% Load weights trained on MS-COCO
model.load_weights(COCO_MODEL_PATH, by_name=True)

# Error
ValueError: Tried to convert 'shape' to a tensor and failed. Error: None values not supported.

I have tried this method but I'm still getting the error
 
![image](https://user-images.githubusercontent.com/94586300/145360017-ff8db264-bb8d-45fc-b3b8-d35d16aa7500.png)

**Comment by farcaz** [comment]
This seems 'model.py' is not yet upgraded and it still has the same legacy code. If you really want to run the scripts, I would advise you to create a fresh virtual environment and try setting up according to the Mask_RCNN first release. Otherwise, you can try upgrading the 'model.py'. I tried the classical version and it is running smooth. In fact, I tried the samples as well. 
Thank you.

**Comment by mlsy123** [comment]
Thanks. I have got it working after creating a new virtual environment.

**Comment by guanhuankang** [comment]
> 

Can you provide your virtual env setting? Like the version of pytotch and cuda. Thanks!

**Comment by johnMinelli** [comment]
> I would advise you to create a fresh virtual environment and try setting up according to the Mask_RCNN first release

Did you use the requirements detailed in the README i.e. tf 1.13 with python 3.4/5/6?
