### ISSUE TITLE
Detection result is error when input batch size > 1

### ISSUE THREAD

**Issue by PaulChongPeng** [matterport/Mask_RCNN#31]
I use 'model.detect(image_batch, verbose=1)' to detect images, but I find the result is error.
The results of '1.jpg' and '10.jpg' are same.
I check the code and find that the value of input is ok but the value of detections[0] and detections[1] are duplicate.

code in model.py

    detections, mrcnn_class, mrcnn_bbox, mrcnn_mask, \
            rois, rpn_class, rpn_bbox =\
        self.keras_model.predict([molded_images, image_metas], verbose=0)

my test code

    image_batch = []
    image_name_batch = []

    image_path_1 = './1.jpg'
    image_batch.append(skimage.io.imread(image_path_1))
    image_path_10 = './10.jpg'
    image_batch.append(skimage.io.imread(image_path_10))

    results = model.detect(image_batch, verbose=1)
    for j in range(len(image_batch)):
        r = results[j]
        visualize.display_instances(image_batch[j], r['rois'], r['masks'], r['class_ids'],
                          coco_class_names, r['scores'],title=image_name_batch[j])

**Comment by waleedka** [comment]
You're right. The DetectionLayer currently supports one image per batch only. There is a TODO comment about that in model.py:

```
class DetectionLayer(KE.Layer):
    """Takes classified proposal boxes and their bounding box deltas and
    returns the final detection boxes.

    # TODO: Add support for batch_size > 1
```

This fix is easy, but it slipped through the cracks because all the testing was done on batch size of 1. In the call() function, the variable `b` is set to 0 so it always reads the first row in the batch only. This should be replaced with a loop and then the results stacked together. I'll try to fix this in the weekend. Or if you'd like to take a stab at it, I'd be happy to review your fix.

**Comment by PaulChongPeng** [comment]
I will try to fix it

**Comment by PaulChongPeng** [comment]
I have created a pull request to fix the bug.
Please review it.

**Comment by waleedka** [comment]
Looks good. Thank you. Merged.

**Comment by raghavgurbaxani** [comment]
@PaulChongPeng @waleedka Could you mention how to perform predictions over a batch of images.
