### ISSUE TITLE
Why do it need to reshape loss with the shape of [1,1] in mrcnn_bbox_loss_graph, mrcnn_mask_loss_graph

### ISSUE THREAD

**Issue by Superlee506** [matterport/Mask_RCNN#313]
![image](https://user-images.githubusercontent.com/13114675/37178317-1304af6e-22f0-11e8-9bd4-b276c1af0071.png)
I'm confused about the reshape in these two place. Any suggestion will be appreciated.

**Comment by Superlee506** [comment]
Any suggestion ?

**Comment by FruVirus** [comment]
@Superlee506 

The distinction between class loss vs. BB and mask losses is that the former is a loss that is dataset-specific while the latter losses are class-specific. 

rpn_class_loss_graph() and mrcnn_class_loss_graph() outputs a single scalar value between we are computing the loss for each ROI w.r.t. to its ground-truth class.

rpn_bbox_loss_graph(), mrcnn_bbox_loss_graph(), and mrcnn_mask_loss_graph() outputs a single scalar value as well but these losses are class-specific and a single dataset has (typically) more than one class.

So why doesn't rpn_bbox_loss_graph() reshape to [1, 1] like the other two? Because in the RPN, the two classes are background and foreground and we don't calculate a loss for BB regression for background objects. Hence, we only have one class in rpn_bbox_loss_graph(). Thus, we don't need to reshape to [1,  1]. 

In mrcnn_bbox_loss_graph() and mrcnn_mask_loss_graph(), we are now in the object detection network (ODN) part of Mask R-CNN. These two functions calculate the class-specific losses and each [1, 1] output plane is interpreted as a score for each class of interest.

Also, recall that fpn_classifier_graph() and build_fpn_mask_graph() are fully convolutional, with one output plane for every ROI.

**Comment by Superlee506** [comment]
@FruVirus Thank you for you detailed reply. After I read it, I'm still confused. Because in my opinion, loss is  always a scalar. If I don't reshape these two losses with [1,1],  will the final results be wrong?

**Comment by FruVirus** [comment]
@Superlee506 

You are right that losses are scalar values and in this case the losses are scalars as well. I suppose the easiest way to find out the answer to your question is just to try it without the reshape and see if there are errors.

**Comment by Superlee506** [comment]
@FruVirus I comment these reshape codes and there isn't errors in the training progress.
