### ISSUE TITLE
The detection speed reduce when batch size increasing

### ISSUE THREAD

**Issue by PaulChongPeng** [matterport/Mask_RCNN#34]
I test the detection speed with different batch_size, and it's surprising that the detection speed reduce when batch size increasing.
Then I check my device , and find it's OK.
Finally, I find batch_slice's annotation in utils.py.

    Batch Slicing
    Some custom layers support a batch size of 1 only, and require a lot of work
    to support batches greater than 1. This function slices an input tensor
    across the batch dimension and feeds batches of size 1. Effectively,
    an easy way to support batches > 1 quickly with little code modification.
    In the long run, it's more efficient to modify the code to support large
    batches and getting rid of this function. Consider this a temporary solution

Although I have changed the code in DetectionLayer, it's the fact that the model support batch size > 1 superficially.

And I also find a bug, if we feed images of which the length is smaller than config.BATCH_SIZE to the function detect(self, images, verbose=0), program will raise exception.
I add "assert" to avoid it.

    assert len(images) == self.config.BATCH_SIZE, "len(images) must be equal to BATCH_SIZE"

**Comment by waleedka** [comment]
You're right, but there is more to it. The delay is likely not related to batch slicing, at least not directly.

First, let me describe batch slicing.  Batch slicing is done using the `batch_slice()` function. It adds a bit of overhead, but it shouldn't be noticeable. Note that batch slicing does *NOT* mean that the examples are processed serially in a loop. They are still processed in parallel.

The `batch_slice()` function duplicates the TF operations to have an op for each example. Let's say you're adding two tensors and need to use the ADD operation. An efficient implementation is to have ADD work on the full batch. This is easy for simple ops, but hard for complex ones. So `batch_slice` creates a copy of the ADD op for each example. If your batch size is 8, then you'll have 8 ADD ops. TensorFlow is designed to parallelize operations automatically, so the 8 ops should run in parallel anyway. There is a bit of overhead for splitting the batch and then merging it afterwards, but that's really small. There is a bit of added memory to store the 8 ops, but that should be small as well since ops don't store data.

The code that you updated in the DetectionLayer doesn't use `batch_slize()`. But rather it's a normal Python loop that calls the refine_detections() function. It's not batch slicing, but it does run serially in a loop. 

If fast detection is important then the right solution is to convert `refine_detections()` to tensorflow. We can parallelize it using `batch_slice` and it should still be fast because it will run in parallel. 

Most of the operations in `refine_detections` have corresponding TF ops. And the Python functions there have corresponding TF functions as well in the code. 
* apply_box_deltas() has a corresponding TF version in apply_box_deltas_graph()
* clip_to_window() has a corresponding TF version in clip_boxes_graph()
* non_max_suppression() has a corresponding builtin function in TF as well

So converting the function shouldn't be too hard, but not trivial either. I'm happy to help if you want to attempt this. I would do it but currently have a few other tasks that I need to get done first.

And, thank you for the pull request. I merged it.

**Comment by PaulChongPeng** [comment]
Thanks for your help!

**Comment by waleedka** [comment]
There is now a PR in progress to replace the last remaining Python layer with TF code. https://github.com/matterport/Mask_RCNN/pull/167

**Comment by Cpruce** [comment]
Hi @PaulChongPeng the fix is in master now
