### ISSUE TITLE
Docker image for GPU support

### ISSUE THREAD

**Issue by namankothari** [matterport/Mask_RCNN#360]
The docker image shared in the project supports CPU. Is there a docker image that can be used to run the code on GPU? Please share.

**Comment by CoolJack11** [comment]
I use  tensorflow/tensorflow:latest-devel-gpu-py3 because I couldn't find any images that had all that is needed. Then i just manually installed keras , opencv (I use it, not necessary) and other python tools that are listed on this project. After that you can commit the container as a new image so you have everything necessary in your new image.

**Comment by briansp2020** [comment]
https://github.com/ufoym/deepo
