### ISSUE TITLE
Performance Improvement 

### ISSUE THREAD

**Issue by filipetrocadoferreira** [matterport/Mask_RCNN#40]
Firstly I want to congratulate you for this amazing work.

In your opinion, where modifications will impact most the performance (frame rate) of the method. 

I'm thinking going with a smaller backbone network (for instance, squeeze net). Do you think it's there the performance bottleneck?

**Comment by waleedka** [comment]
A smaller backbone will definitely help, but it's hard for me to estimate how much impact that would have on the overall speed. You can try ResNet50 first because the code supports it already (see discussion in https://github.com/matterport/Mask_RCNN/issues/5), and that would help you estimate the effect of the backbone on the overall speed.

Another improvement is to convert some of the remaining Python code to TF as discussed in https://github.com/matterport/Mask_RCNN/issues/34

You can also play with several parameters to control the balance between speed and accuracy. 
* Smaller images will process much faster
* You can reduce the number of anchors (increase the anchor stride)
* You can reduce the number of proposals to process (default is 1000) but you can go lower and not lose significant accuracy.
