### ISSUE TITLE
TRAINING ON CUSTOM DATASET

### ISSUE THREAD

**Issue by rmmal** [matterport/Mask_RCNN#428]
I have a dataset , and I want to convert my labels into coco format.

I read all the posts and issues but still very confused.

My dataset has images and labels
Labels are in format of (x,y,w,h)

Can someone tell me in steps how can i convert these labels into coco format ?

**Comment by stanathong** [comment]
@rmmal 
Apoloy for jumping in but I just would like to share.
If you would like to train your dataset using the provided code, it is not necessary for you to convert your dataset (i.e. your label / mask / bouding box) into the coco format.

What you have to do is to start off with https://github.com/matterport/Mask_RCNN/tree/master/samples/shapes/train_shapes.ipynb.

There are code that you need to modify in order to load/train your dataset.

1) Subclass Config as seen in class ShapesConfig in which you modify NAME to be your dataset name i.e. "fruit" or "furniture" whatever match your dataset. The essential parameters to change is IMAGES_PER_GPU, NUM_CLASSES (1 background + the number of your classes). You can delete other parameters if you are unclear as it will use the default setting for COCO dataset.

2) Subclass Dataset as seen in class ShapesDataset. Here you have to modify load_shapes() to add your images, bouding box into the its local database (defined as image_info variable in class Dataset). What you need to do is to modify load_image() to the way you read your image. If you know the path or url of hte image, you can delete this and only add "path" when you call add_image() in your modify load_shapes() function. Then modify load_mask() function that define how mask are generated. Note that if you have a polygon shape label i.e. a list of coordinates (x,y), you could simply generate mask by using  cv2.fillPoly() function see example implemention in draw_shape() for triangle. From what you said your label is in the format of (x,y,w,h), simply use cv2.rectangle() to generate masks, again see draw_shape() for 'square'.

All in all, that's what you need.

Just try to run train_shapes.ipynb and what I have said will be more clearer to you. Good luck!

**Comment by waleedka** [comment]
In addition the great answer from @stanathong take a look at this post that explains the process:
https://engineering.matterport.com/splash-of-color-instance-segmentation-with-mask-r-cnn-and-tensorflow-7c761e238b46
