### ISSUE TITLE
Hyper parameter optimization

### ISSUE THREAD

**Issue by Zumbalamambo** [matterport/Mask_RCNN#445]
Thanks for your amazing work . Im trying to segment multiple smaller objects of few mm size contained in a bigger object. The problem arises when the size is so small. Im following BaloonConfig exactly to train the network. The model performs well but not always. it fails to detect certain smaller objects.  Im wondering if changing RPN_ANCHOR_SCALES to (8, 16, 32, 64, 128) could work

May I know How should I choose the various hyper parameters for detecting or masking such minute objects? If you can share your valuable suggestions, it will be helpful to gain deeper insights. Thanks.

**Comment by waleedka** [comment]
Making the anchors smaller might help. You can start with anchors of size 4 or 6 instead of 8 and see if that helps. 

The other challenge for small objects is that the first two layers of ResNet two subsampling twice (a conv layer with stride of two, followed by max pooling with stride of 2), so the anchors are 4 pixels apart at a minimum, which makes it easy to miss small objects. One solution is to change the network architecture a bit to reduce early strides, or the alternative is to scale up the input image. 

See the `nucleus` example. It uses the second approach, scaling up the image to 2x using the `IMAGE_MIN_SCALE` setting.

https://github.com/matterport/Mask_RCNN/tree/master/samples/nucleus

**Comment by Zumbalamambo** [comment]
@waleedka Thank you so much. I tried doing so but still the accuracy is bit less. If I use imagenet, will it improve the accuracy of smaller object?   will it be able detect smaller object if I train last four layers as in coco example?
