### ISSUE TITLE
Replacement instead of augmentation?

### ISSUE THREAD

**Issue by YubinXie** [matterport/Mask_RCNN#467]
In the new augmentation function, I noticed that the augmentation is applied in the generator part as a replacement of original image form. Does this mean augmentation image will replace the original image, instead of increasing the overall training image amount?
It is possible that I mis-understand the codes. It would be nice if someone can sort this out. Thanks.

**Comment by YubinXie** [comment]
After some digging, it seems that the data was repeated generated instead of one-run. So this is augmentation instead of replacement!

**Comment by ash1995** [comment]
@YubinXie  So the augmentation increases the image count?

**Comment by YubinXie** [comment]
No. Augmentation is by chance, not by number.

**Comment by ericq** [comment]
The number of input images did get increased... a bit tricky because it's done implicitly by the data generator. The data generator is an infinite loop that processes, including augmentation operation, input images and returns processed (augmented) result to the training once it filled up one batch. Within each process operation, each original image is _replaced_ with an augmented image .... but the looped/repeated operations do add new images from a holistic view.

[this long article discusses this](https://www.pyimagesearch.com/2019/07/08/keras-imagedatagenerator-and-data-augmentation/)

**Comment by suchiz** [comment]
But it's still random right ? The augmentation is done during load_image_gt. And even if the augment parameter is set to True, there is a randrange(0,1) before the operation. Which means that if I have a dataset of 600 images, and want them to be augmented by a flip operation, it would in theory double my dataset to 1200. With a batch_size of 1, it's 1200 step_per_epoch. But because of this randrange, nothing warranties that an image will be seen twice as the same image, or one time as normal and one time as augmented ...
