### ISSUE TITLE
Any plans on splitting model.py?

### ISSUE THREAD

**Issue by im9uri** [matterport/Mask_RCNN#65]
Hi waleedka,

The file model.py is quite large at over 2200 lines, and could be split up into multiple files for better accessibility, since it already has multiple components such as Resnet, RPN, and FPN, as well as other utility functions. I was wondering if you had any plans to refactor the code.

Also, is the issue page the best place to ask questions about the code?

Thanks.

**Comment by waleedka** [comment]
Yes, it's okay to ask questions in the issues. I don't know of a better alternative, like a forum, in Github. 

When I read other repos that split the code into many files, I often find them harder to read because I have to guess where each function is, especially in repos that take it to the extreme and have a lot of files with 50 or less lines of code each. There is a certain simplicity to being able to just drop the `model.py` file into your own code and start using it. 

With that said, I'm open to splitting the file if there is good case beyond "file is too long". With modern editors that support bookmarks, quick search, and split panes, it's easy to work with big files, often easier than working with multiple small files. A good reason to split, for me, would be if parts of the code are often imported without the whole model (like splitting `config.py` in it's own file), or if you want to make certain parts easy to replace, and so on.

**Comment by im9uri** [comment]
Thanks for the info.
