### ISSUE TITLE
UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. 

### ISSUE THREAD

**Issue by ad12** [matterport/Mask_RCNN#656]
I am getting the warning below

```
UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
```

Is this warning common, or could there be an issue with loading the image and mask?

**Comment by schmidje** [comment]
Looks like several people see this warning, myself included. In my case I can run a training without issues although I am seeing odd gpu scalability behavior... So I would be happy to not see any warnings :)

What is your tf version?

**Comment by ad12** [comment]
@schmidje thanks for your response! Running tf 1.6.0 backend with keras 2.1.3. Unfortunately, training isn't working. I am getting the error described in issue #644 . 

I am training on a CPU currently to just test out the code before deploying it to a server. Any suggestions on how to tackle that issue?

**Comment by schmidje** [comment]
The issue #644  you reference returns the message _"tensorflow.python.framework.errors_impl.InvalidArgumentError: flat indices[5, :] = [0, 248102] does not index into param (shape: [1,20730,4])."_ which looks different form yours so I am not sure it is the same issue. You see the warning you mentioned + the error of issue #644 causing a crash?

I though the error was related to recent tf (I am using 1.8) but it looks like the problem is not coming from the version of tf... : (

**Comment by waleedka** [comment]
@ad12 This warning has been there from the first iterations of this model on TF 1.3 or so. I'm not sure which operation is causing it because TF doesn't give enough details, but it doesn't seem to be a problem and I never had an issue that I can link to this warning.

**Comment by ad12** [comment]
@schmidje Yup, seeing both the warning and the crash, but you're right, they probably aren't related.

@waleedka Makes sense. Do you have any insights on #644 ?

Thank you both!
