### ISSUE TITLE
Layer roi_align_classifier was called with an input that isn't a symbolic tensor. 

### ISSUE THREAD

**Issue by idvr** [matterport/Mask_RCNN#881]
How to fix this error in 
“model = modellib.MaskRCNN(mode="inference", model_dir=MODEL_DIR, config=config)”

Window anaconda
TF v1.8
keras 2.2

Thanks.

**Comment by anibalanto** [comment]
Hello! I had the same problem.
I had modified the value of some variables in the sample code / demo.ipynb

`class InferenceConfig(coco.CocoConfig):
    # Set batch size to 1 since we'll be running inference on
    # one image at a time. Batch size = GPU_COUNT * IMAGES_PER_GPU
-    GPU_COUNT = 1
-    IMAGES_PER_GPU = 1
+   GPU_COUNT = 0
+   IMAGES_PER_GPU = 0`

This he had done thinking that having no GPUs was going to influence.
Returning to its original value the problem was solved.

**Comment by idvr** [comment]
@anibalanto 
Modifying it by:

    GPU_COUNT = 0
    IMAGES_PER_GPU = 0
still have the same problem.
After pip install tensorflow==1.3.0 keras==2.0.8,the problem was solved.

**Comment by kongzhiyou** [comment]
> @anibalanto
> Modifying it by:
> 
> ```
> GPU_COUNT = 0
> IMAGES_PER_GPU = 0
> ```
> still have the same problem.
> After pip install tensorflow==1.3.0 keras==2.0.8,the problem was solved.

I try whit the same version, but  the problem stil exists

**Comment by Thommy257** [comment]
any news on this @kongzhiyou?

**Comment by Sofiane23i** [comment]
GPU_COUNT = 0
IMAGES_PER_GPU = 1

**Comment by Sofiane23i** [comment]
GPU_COUNT = 1
IMAGES_PER_GPU = 1

should be work on cpu also
