### ISSUE TITLE
Use only the mask branch of Mask RCNN

### ISSUE THREAD

**Issue by vp1993** [matterport/Mask_RCNN#914]
For a project that I am working on I only need to generate masks for my objects. Is it possible to simplify the architecture by removing the Faster RCNN part that generates bounding boxes and only keep the Mask branch?

**Comment by amin3511** [comment]
its my question too

**Comment by waleedka** [comment]
I'm afraid not. The network generates the bounding boxes first, and then filters them to pick the most accurate ones, and then finally applies the mask branch only on the detected boxes. This arrangement actually makes the network faster because it allows it to run the mask branch (which is a heavy branch) only on the boxes that have already been filtered.

**Comment by amin3511** [comment]
@vp1993 you can go visualize.py
line 135 and replace edgecolor='none' insted of  edgecolor=color

**Comment by AmanuelHirpa** [comment]
I might be too late to reply to you @vp1993 but it might be useful for others. I disagree with @waleedka, in fact, both branches of Mask R-CNN takes input form fifth layer (fixed size feature map) computed after RPN and ROIAlign. At this stage, only the most accurate boxes are presented. thus we can use only the mask branch to do whatever we want to solve with it. I think there is no direct r/ship b/n the first branch of network head(box regression and classification) and the second head(mask branch). Please correct me if am wrong. Thanks.
