### ISSUE TITLE
Continuous training

### ISSUE THREAD

**Issue by JiayingLi** [matterport/Mask_RCNN#920]
Hi everyone,

I'm training my own dataset using Mask_RCNN. My training steps are like the following:
````

model.train(dataset_train, dataset_val, 
            learning_rate=config.LEARNING_RATE, 
            epochs=10, 
            layers='head',
)

model.train(dataset_train, dataset_val, 
            learning_rate=config.LEARNING_RATE/10, 
            epochs=5,
            layers='all',
)
````

But every time when it finished the first step, it did not proceed to the next training step. Is it because memory issue such as I need to release some memory from the last train? 
Anyone has this kind of issue before?

Thanks

**Comment by fastlater** [comment]
@JiayingLi post your error. You dont need to handle the memory issues. If the original script is giving you error, the problem is in your side.

**Comment by heyuanzhen** [comment]
I find the reason.  Say you called model.train(...epochs=i) first, then if you call model.train(...epoch=i), the program will stop. Because the parameter 'epochs' is accumulated.  To solve it, if you want to train i epochs first, then train 2i epochs, you should write like these: model.train(...epochs=i) ... model.train(...epochs=3i), Since 3i - i = 2i.

**Comment by JiayingLi** [comment]
@heyuanzhen I just tested it and you are right! The training steps are working as expected now. 

Thanks for your suggestion. The accumulated epoch is quite tricky though.
